// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPtv1jqjNNww-PB9QByj-qHfxcwGzuKs8',
    appId: '1:993771783319:web:8e392daaa950afd31455d2',
    messagingSenderId: '993771783319',
    projectId: 'restaurant-app-bb19b',
    authDomain: 'restaurant-app-bb19b.firebaseapp.com',
    storageBucket: 'restaurant-app-bb19b.appspot.com',
    measurementId: 'G-0NX2XPSPES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhaLOf4P5mzXEiC-Q8E6-d95d8oxPDY4w',
    appId: '1:993771783319:android:192cf144fac866d11455d2',
    messagingSenderId: '993771783319',
    projectId: 'restaurant-app-bb19b',
    storageBucket: 'restaurant-app-bb19b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDATqSby6yLqUsPH3bIHlLiPgP8SJQ99Zg',
    appId: '1:993771783319:ios:45fb488bebd1f9ad1455d2',
    messagingSenderId: '993771783319',
    projectId: 'restaurant-app-bb19b',
    storageBucket: 'restaurant-app-bb19b.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDATqSby6yLqUsPH3bIHlLiPgP8SJQ99Zg',
    appId: '1:993771783319:ios:e8a4237c4b1dead81455d2',
    messagingSenderId: '993771783319',
    projectId: 'restaurant-app-bb19b',
    storageBucket: 'restaurant-app-bb19b.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
